export const environment = {
  production: true,

  // baseUrl : 'http://buddy.cs.colman.ac.il:8080',
  // usersUrl : 'http://buddy.cs.colman.ac.il:8080/user',
  // plantUrl : 'http://buddy.cs.colman.ac.il:8080/plant',
  // photoUrl : 'http://buddy.cs.colman.ac.il:8080/photo',
  // gardenUrl : 'http://buddy.cs.colman.ac.il:8080/garden',
  // sensorUrl : 'http://buddy.cs.colman.ac.il:8080/sensor',
  // postUrl : 'http://buddy.cs.colman.ac.il:8080/post',
  // commentUrl : 'http://buddy.cs.colman.ac.il:8080/comment',
  baseUrl : 'http://localhost:8080',
  usersUrl : 'http://localhost:8080/user',
  plantUrl : 'http://localhost:8080/plant',
  photoUrl : 'http://localhost:8080/photo',
  gardenUrl : 'http://localhost:8080/garden',
  sensorUrl : 'http://localhost:8080/sensor',
  postUrl : 'http://localhost:8080/post',
  commentUrl : 'http://localhost:8080/comment',
};
